---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: boream-cert-manager
  namespace: "default"
  labels:
    app: cert-manager
    chart: cert-manager-v0.8.1
    release: boream
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
      release: boream
  template:
    metadata:
      labels:
        app: cert-manager
        release: boream
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9402'
    spec:
      serviceAccountName: boream-cert-manager
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-controller:v0.8.1"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=$(POD_NAMESPACE)
          ports:
          - containerPort: 9402
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            
