---
# Source: cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boream-cert-manager
  namespace: "default"
  labels:
    app: cert-manager
    chart: cert-manager-v0.8.1
    release: boream
    heritage: Tiller
