---
# Source: mariadb/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: boream-mariadb
  labels:
    app: "mariadb"
    component: "master"
    chart: "mariadb-5.11.1"
    release: "boream"
    heritage: "Tiller"
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "mariadb"
    component: "master"
    release: "boream"
