---
# Source: mariadb/templates/slave-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: boream-mariadb-slave
  labels:
    app: "mariadb"
    chart: "mariadb-5.11.1"
    component: "slave"
    release: "boream"
    heritage: "Tiller"
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "mariadb"
    component: "slave"
    release: "boream"
