---
# Source: mariadb/templates/tests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: boream-mariadb-tests
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h boream-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
