---
# Source: openfaas/templates/operator-rbac.yaml

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boream-operator
  namespace: "default"
  labels:
    app: openfaas
    chart: openfaas-4.4.0
    component: openfaas-operator
    heritage: Tiller
    release: boream
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boream-operator-rw
  namespace: "openfaas-fn"
  labels:
    app: openfaas
    chart: openfaas-4.4.0
    component: openfaas-operator
    heritage: Tiller
    release: boream
rules:
- apiGroups: ["openfaas.com"]
  resources: ["functions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boream-operator-rw
  namespace: "openfaas-fn"
  labels:
    app: openfaas
    chart: openfaas-4.4.0
    component: openfaas-operator
    heritage: Tiller
    release: boream
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: boream-operator-rw
subjects:
- kind: ServiceAccount
  name: boream-operator
  namespace: "default"