---
# Source: kube-ops-view/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-ops-view
    chart: kube-ops-view-0.7.0
    heritage: Tiller
    release: boream
  name: boream-kube-ops-view