---
# Source: cert-manager/charts/webhook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boream-webhook
  namespace: "default"
  labels:
    app: webhook
    chart: webhook-v0.8.1
    release: boream
    heritage: Tiller
