---
# Source: cert-manager/charts/webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: boream-webhook
  namespace: "default"
  labels:
    app: webhook
    chart: webhook-v0.8.1
    release: boream
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: webhook
    release: boream
