version: "3"

services:
  clair:
    image: arminc/clair-local-scan:v2.0.6
    restart: always
    expose:
      - "6060"
    networks:
      - scanning
    links:
      - db:postgres
    depends_on:
      - db

  db:
    image: arminc/clair-db:2019-04-03
    expose:
      - "5432"
    networks:
      - scanning

networks:
  scanning: